// <auto-generated />
// Generated by tools/regenerate-baseline.sh from the SQLite migrations the PostgreSQL baseline replaces.
namespace Jellyfin.Database.Providers.PostgreSQL.Migrations;

/// <summary>
/// The SQLite migrations whose schema changes are part of the PostgreSQL baseline.
/// </summary>
internal static class PostgreSqlBaselineSquashedIds
{
    /// <summary>
    /// Gets the migration ids.
    /// </summary>
    public static string[] Ids { get; } =
    [
        "20200514181226_AddActivityLog",
        "20200613202153_AddUsers",
        "20200728005145_AddDisplayPreferences",
        "20200905220533_FixDisplayPreferencesIndex",
        "20201004171403_AddMaxActiveSessions",
        "20201204223655_AddCustomDisplayPreferences",
        "20210320181425_AddIndexesAndCollations",
        "20210407110544_NullableCustomPrefValue",
        "20210814002109_AddDevices",
        "20221022080052_AddIndexActivityLogsDateCreated",
        "20230526173516_RemoveEasyPassword",
        "20230626233818_AddTrickplayInfos",
        "20230923170422_UserCastReceiver",
        "20240729140605_AddMediaSegments",
        "20240928082930_MarkSegmentProviderIdNonNullable",
        "20241020103111_LibraryDbMigration",
        "20241111131257_AddedCustomDataKey",
        "20241111135439_AddedCustomDataKeyKey",
        "20241112152323_FixAncestorIdConfig",
        "20241112232041_FixMediaStreams",
        "20241112234144_FixMediaStreams2",
        "20241113133548_EnforceUniqueItemValue",
        "20250202021306_FixedCollation",
        "20250204092455_MakeStartEndDateNullable",
        "20250214031148_ChannelIdGuid",
        "20250326065026_AddInheritedParentalRatingSubValue",
        "20250327101120_AddKeyframeData",
        "20250327171413_AddHdr10PlusFlag",
        "20250331182844_FixAttachmentMigration",
        "20250401142247_FixAncestors",
        "20250405075612_FixItemValuesIndices",
        "20250609115616_DetachUserDataInsteadOfDelete",
        "20250622170802_BaseItemImageInfoDateModifiedNullable",
        "20250714044826_ResetJournalMode",
        "20250913211637_AddProperParentChildRelationBaseItemWithCascade",
        "20250925203415_ExtendPeopleMapKey",
        "20260113102337_AddLinkedChildrenTable",
        "20260113203012_ChangeOwnerIdToGuid",
        "20260113233000_AddForeignKeyToOwnerId",
        "20260113233500_DropExtraIdsColumn",
        "20260116114245_AddLatestItemsDateCreatedIndexes",
        "20260118182305_AddIndicesToImageInfo",
        "20260130232147_AddBaseItemNameIndex",
        "20260206224832_IndexOptimizations",
        "20260215201634_ChangePrimaryVersionIdToGuid",
        "20260308123920_AddTypeCleanNameIndex",
        "20260504075755_AddPartialIndexForItemCounts",
        "20260522092303_AddNormalizedUsername",
        "20260524120336_AddUniqueNormalizedUsernameIndex",
        "20260723111547_AllowDuplicatePlaylistChildren",
        "20260724185102_AddPrimaryVersionIdIndex",
        "20260728170000_AddPeopleNameLowerIndex",
        "20260728182152_AddPeopleItemMapCoveringIndex",
        "20260812050902_AddMediaStreamFilterIndex",
        "20260815063607_RemoveOrphanedUserPermissionsAndPreferences",
        "20260925234214_ExtendBrowseSortIndexWithName",
    ];
}
