using System;
using System.Data.Common;
using System.Diagnostics.CodeAnalysis;
using System.Text;
using Microsoft.EntityFrameworkCore.Diagnostics;

namespace Jellyfin.Database.Providers.PostgreSQL.Query;

/// <summary>
/// Makes PostgreSQL check group representatives against a hash table instead of joining against them.
/// </summary>
/// <remarks>
/// Grouped item queries select one id per group with <c>id IN (SELECT MIN(...) ... GROUP BY ...)</c>. PostgreSQL turns
/// that into a semi join, underestimates how many ids the subquery returns once access filters are involved, and
/// compares every item with every representative (43 s instead of 60 ms on 50 000 items). Written as
/// <c>id IN (SELECT ...) IS TRUE</c> the subquery is not turned into a join: it runs once into a hash table that every
/// item is looked up in. Only subqueries that select an id aggregate from <see cref="UuidMinMaxTranslator"/> are
/// rewritten; those never reference the outer query and never return NULL, so the result cannot change.
/// </remarks>
internal sealed class GroupRepresentativeInterceptor : DbCommandInterceptor
{
    private const string AggregateMarker = "COLLATE \"C\")::uuid";

    private GroupRepresentativeInterceptor()
    {
    }

    /// <summary>
    /// Gets the interceptor.
    /// </summary>
    public static GroupRepresentativeInterceptor Instance { get; } = new();

    /// <inheritdoc />
    [SuppressMessage("Security", "CA2100:Review SQL queries for security vulnerabilities", Justification = "The statement is generated by Entity Framework Core and only restructured; values stay parameters.")]
    public override DbCommand CommandInitialized(CommandEndEventData eventData, DbCommand result)
    {
        result.CommandText = Rewrite(result.CommandText);
        return result;
    }

    /// <summary>
    /// Rewrites group representative subqueries in a SQL statement.
    /// </summary>
    /// <param name="sql">The SQL statement.</param>
    /// <returns>The rewritten statement, or the same instance when nothing matched.</returns>
    internal static string Rewrite(string sql)
    {
        if (!sql.Contains(AggregateMarker, StringComparison.Ordinal))
        {
            return sql;
        }

        StringBuilder? builder = null;
        var copied = 0;
        var searchFrom = 0;
        while (true)
        {
            var match = sql.IndexOf(" IN (", searchFrom, StringComparison.Ordinal);
            if (match < 0)
            {
                break;
            }

            var open = match + 4;
            searchFrom = open + 1;
            var close = FindClosingParenthesis(sql, open);
            if (close < 0 || EndsWithNot(sql, match) || !SelectsIdAggregate(sql, open + 1, close))
            {
                continue;
            }

            builder ??= new StringBuilder(sql.Length + 32);
            builder.Append(sql, copied, close + 1 - copied).Append(" IS TRUE");
            copied = close + 1;
            searchFrom = close + 1;
        }

        return builder is null ? sql : builder.Append(sql, copied, sql.Length - copied).ToString();
    }

    private static bool EndsWithNot(string sql, int index)
        => index >= 3 && string.CompareOrdinal(sql, index - 3, "NOT", 0, 3) == 0;

    private static bool SelectsIdAggregate(string sql, int start, int end)
    {
        var body = sql.AsSpan(start, end - start).TrimStart();
        if (!body.StartsWith("SELECT MIN(", StringComparison.Ordinal) && !body.StartsWith("SELECT COALESCE(MIN(", StringComparison.Ordinal))
        {
            return false;
        }

        var from = body.IndexOf("FROM ", StringComparison.Ordinal);
        return from > 0 && body[..from].IndexOf(AggregateMarker, StringComparison.Ordinal) >= 0;
    }

    private static int FindClosingParenthesis(string sql, int open)
    {
        var depth = 0;
        for (var i = open; i < sql.Length; i++)
        {
            switch (sql[i])
            {
                case '\'':
                case '"':
                    // Skip quoted text; a doubled quote stays inside the literal or identifier.
                    var quote = sql[i];
                    for (i++; i < sql.Length; i++)
                    {
                        if (sql[i] == quote)
                        {
                            if (i + 1 < sql.Length && sql[i + 1] == quote)
                            {
                                i++;
                            }
                            else
                            {
                                break;
                            }
                        }
                    }

                    break;
                case '(':
                    depth++;
                    break;
                case ')':
                    if (--depth == 0)
                    {
                        return i;
                    }

                    break;
            }
        }

        return -1;
    }
}
