#!/usr/bin/env bash
# Regenerates the PostgreSQL baseline migration from the current model.
# Only valid while the baseline is the sole PostgreSQL migration. Run from anywhere inside the repository.
set -euo pipefail

ROOT="$(git rev-parse --show-toplevel)"
PG="src/Jellyfin.Database/Jellyfin.Database.Providers.PostgreSQL"
SQLITE="src/Jellyfin.Database/Jellyfin.Database.Providers.Sqlite"
BASELINE_ID="20200101000000_PostgreSqlBaseline"
cd "$ROOT"

shopt -s nullglob
others=()
for f in "$PG"/Migrations/*.cs; do
  case "$(basename "$f")" in
    "$BASELINE_ID".cs|"$BASELINE_ID".Designer.cs|JellyfinDbContextModelSnapshot.cs|PostgreSqlBaselineSquashedIds.cs) ;;
    *) others+=("$f") ;;
  esac
done
if [ ${#others[@]} -gt 0 ]; then
  echo "Refusing to regenerate: PostgreSQL migrations other than the baseline exist: ${others[*]}" >&2
  exit 1
fi

dotnet tool restore >/dev/null
# Keep the squashed id list: the provider needs it to build, and it is rewritten below.
rm -f "$PG/Migrations/$BASELINE_ID.cs" "$PG/Migrations/$BASELINE_ID.Designer.cs" "$PG/Migrations/JellyfinDbContextModelSnapshot.cs"
rm -rf "$PG/Jellyfin"
dotnet ef migrations add PostgreSqlBaseline \
  --project "$PG" --startup-project "$PG" --context JellyfinDbContext \
  --output-dir Migrations --namespace Jellyfin.Database.Providers.PostgreSQL.Migrations >/dev/null

# dotnet-ef places the snapshot in a folder derived from the namespace.
snapshot="$(find "$PG" -name JellyfinDbContextModelSnapshot.cs -not -path "$PG/Migrations/*" | head -n 1)"
if [ -n "$snapshot" ]; then
  mv "$snapshot" "$PG/Migrations/JellyfinDbContextModelSnapshot.cs"
  rm -rf "$PG/Jellyfin"
fi

generated="$(ls "$PG"/Migrations/*_PostgreSqlBaseline.cs)"
generated_id="$(basename "$generated" .cs)"
mv "$PG/Migrations/$generated_id.cs" "$PG/Migrations/$BASELINE_ID.cs"
mv "$PG/Migrations/$generated_id.Designer.cs" "$PG/Migrations/$BASELINE_ID.Designer.cs"
perl -pi -e "s/\\[Migration\\(\"$generated_id\"\\)\\]/[Migration(\"$BASELINE_ID\")]/" "$PG/Migrations/$BASELINE_ID.Designer.cs"

# Up(): append the objects the model cannot declare. Down(): the baseline cannot be reverted.
perl -0pi -e '
  s/(protected override void Up\(MigrationBuilder migrationBuilder\)\n        \{\n.*?)(\n        \}\n\n        \/\/\/ <inheritdoc \/>\n        protected override void Down\(MigrationBuilder migrationBuilder\)\n        \{\n).*?(\n        \}\n    \}\n\}\n?)\z/$1\n\n            PostgreSqlBaselineSql.Apply(migrationBuilder);$2            throw new NotSupportedException("The PostgreSQL baseline cannot be reverted. Restore a pg_dump backup instead.");$3/s
    or die "baseline anchors not found\n";
' "$PG/Migrations/$BASELINE_ID.cs"
# The repository expects UTF-8 without a byte order mark in files that are not generated.
perl -0pi -e 's/\A\xEF\xBB\xBF//' "$PG/Migrations/$BASELINE_ID.cs"
grep -q "using System;" "$PG/Migrations/$BASELINE_ID.cs" || perl -0pi -e 's/\A/using System;\n/' "$PG/Migrations/$BASELINE_ID.cs"

# The SQLite migrations the baseline replaces.
{
  echo "// <auto-generated />"
  echo "// Generated by tools/regenerate-baseline.sh from the SQLite migrations the PostgreSQL baseline replaces."
  echo "namespace Jellyfin.Database.Providers.PostgreSQL.Migrations;"
  echo ""
  echo "/// <summary>"
  echo "/// The SQLite migrations whose schema changes are part of the PostgreSQL baseline."
  echo "/// </summary>"
  echo "internal static class PostgreSqlBaselineSquashedIds"
  echo "{"
  echo "    /// <summary>"
  echo "    /// Gets the migration ids."
  echo "    /// </summary>"
  echo "    public static string[] Ids { get; } ="
  echo "    ["
  grep -ho '\[Migration("[^"]*")\]' "$SQLITE"/Migrations/*.Designer.cs | sed -E 's/\[Migration\("([^"]*)"\)\]/        "\1",/' | LC_ALL=C sort
  echo "    ];"
  echo "}"
} > "$PG/Migrations/PostgreSqlBaselineSquashedIds.cs"

printf '*.Designer.cs linguist-generated=true\nJellyfinDbContextModelSnapshot.cs linguist-generated=true\nPostgreSqlBaselineSquashedIds.cs linguist-generated=true\n' > "$PG/Migrations/.gitattributes"
echo "Regenerated $PG/Migrations/$BASELINE_ID"
